// lib/presets.mjs — 34 передналаштованих LLM-провайдери.
// Конвенція: baseURL — те, до чого адаптер додає свій шлях
//   openai     -> + /chat/completions
//   anthropic  -> + /messages
//   gemini     -> + /models/{model}:streamGenerateContent
//   cohere     -> + /v2/chat
//   azure      -> + /openai/deployments/{model}/chat/completions?api-version=...
//   mock       -> локальний офлайн-рушій (без ключа)

export const API_STYLES = {
  openai: "OpenAI-сумісний",
  anthropic: "Anthropic Messages",
  gemini: "Google Gemini",
  cohere: "Cohere v2",
  azure: "Azure OpenAI",
  mock: "Локальний демо-рушій",
};

export const PROVIDER_PRESETS = [
  {
    id: "openrouter", name: "OpenRouter", category: "Агрегатори", apiStyle: "openai",
    baseURL: "https://openrouter.ai/api/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://openrouter.ai/keys", docs: "https://openrouter.ai/docs",
    extraHeaders: { "HTTP-Referer": "http://localhost", "X-Title": "Cartel Radar" },
    models: ["openai/gpt-6-astra", "anthropic/claude-sonnet-5", "anthropic/claude-opus-5", "google/gemini-3.8-flash", "x-ai/grok-4.6", "deepseek/deepseek-v4-pro", "qwen/qwen3.8-max-0902", "moonshotai/kimi-k3", "z-ai/glm-5.3", "minimax/minimax-m3", "meta-llama/llama-4-maverick", "meta-llama/llama-3.3-70b-instruct"],
    notes: "Один ключ — усі топові моделі. Найшвидший спосіб стартувати.",
  },
  {
    id: "openai", name: "OpenAI", category: "Першорядні", apiStyle: "openai",
    baseURL: "https://api.openai.com/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://platform.openai.com/api-keys", docs: "https://platform.openai.com/docs",
    models: ["gpt-6-astra", "gpt-6-astra-pro", "gpt-5.6-luna", "gpt-5.6-luna-pro", "gpt-5.6-terra-pro"],
    notes: "Топова модель — для досьє, дешевша — для масового скринінгу. Точні назви дивіться кнопкою «Підтягнути моделі».",
  },
  {
    id: "anthropic", name: "Anthropic Claude", category: "Першорядні", apiStyle: "anthropic",
    baseURL: "https://api.anthropic.com/v1", authStyle: "x-api-key", keyRequired: true,
    keyUrl: "https://console.anthropic.com/settings/keys", docs: "https://docs.anthropic.com",
    extraHeaders: { "anthropic-version": "2023-06-01" },
    models: ["claude-opus-5", "claude-sonnet-5", "claude-fable-5.1", "claude-opus-4.8", "claude-haiku-4-5"],
    notes: "Найкращий на довгих аналітичних досьє. Haiku — дешевий скринінг.",
  },
  {
    id: "gemini", name: "Google Gemini (AI Studio)", category: "Першорядні", apiStyle: "gemini",
    baseURL: "https://generativelanguage.googleapis.com/v1beta", authStyle: "query", authParam: "key",
    keyRequired: true, keyUrl: "https://aistudio.google.com/apikey", docs: "https://ai.google.dev/gemini-api/docs",
    models: ["gemini-3.8-flash", "gemini-3.7-flash", "gemini-3.5-flash", "gemini-3.5-flash-lite", "gemini-2.5-pro"],
    notes: "Підтримує зображення (аналіз прев'ю). Щедрий безкоштовний ліміт.",
  },
  {
    id: "vertex", name: "Google Vertex AI", category: "Хмарні", apiStyle: "gemini",
    baseURL: "https://{region}-aiplatform.googleapis.com/v1/projects/{project}/locations/{region}/publishers/google",
    authStyle: "bearer", keyRequired: true,
    fields: [{ key: "region", label: "Регіон", placeholder: "us-central1", default: "us-central1" },
             { key: "project", label: "Project ID", placeholder: "my-gcp-project" }],
    keyUrl: "https://console.cloud.google.com/apis/credentials", docs: "https://cloud.google.com/vertex-ai/docs",
    models: ["gemini-3.8-flash", "gemini-3.5-flash", "gemini-2.5-pro"],
    notes: "Потрібен OAuth-токен (не API-ключ) або проксі. Регіон і Project ID підставляються у URL.",
  },
  {
    id: "xai", name: "xAI Grok", category: "Першорядні", apiStyle: "openai",
    baseURL: "https://api.x.ai/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://console.x.ai", docs: "https://docs.x.ai",
    models: ["grok-4.6", "grok-4.5", "grok-4.3", "grok-4.20"],
    notes: "Сильний у трендах та актуальних подіях.",
  },
  {
    id: "deepseek", name: "DeepSeek", category: "Першорядні", apiStyle: "openai",
    baseURL: "https://api.deepseek.com/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://platform.deepseek.com/api_keys", docs: "https://api-docs.deepseek.com",
    models: ["deepseek-v4-pro", "deepseek-v4.1-flash", "deepseek-v4-flash-0731", "deepseek-chat", "deepseek-reasoner"],
    notes: "Найдешевший якісний мас-скринінг. Ідеальний для стадії 2.",
  },
  {
    id: "mistral", name: "Mistral AI", category: "Першорядні", apiStyle: "openai",
    baseURL: "https://api.mistral.ai/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://console.mistral.ai/api-keys", docs: "https://docs.mistral.ai",
    models: ["mistral-medium-3-5", "mistral-large-latest", "mistral-small-2603", "devstral-2512", "codestral-latest"],
    notes: "Mistral Large — добрий баланс ціни й аналітики.",
  },
  {
    id: "groq", name: "Groq", category: "Швидкі", apiStyle: "openai",
    baseURL: "https://api.groq.com/openai/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://console.groq.com/keys", docs: "https://console.groq.com/docs",
    models: ["llama-3.3-70b-versatile", "llama-3.1-8b-instant", "moonshotai/kimi-k2-instruct", "openai/gpt-oss-120b", "qwen/qwen3-32b"],
    notes: "Найшвидші токени — масовий скринінг 100+ кандидатів за хвилини.",
  },
  {
    id: "cerebras", name: "Cerebras", category: "Швидкі", apiStyle: "openai",
    baseURL: "https://api.cerebras.ai/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://cloud.cerebras.ai", docs: "https://inference-docs.cerebras.ai",
    models: ["llama-3.3-70b", "llama3.1-8b", "qwen-3-235b-a22b-instruct-2507", "gpt-oss-120b"],
    notes: "Екстремальна швидкість (1000+ ток/с).",
  },
  {
    id: "together", name: "Together AI", category: "Швидкі", apiStyle: "openai",
    baseURL: "https://api.together.xyz/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://api.together.ai/settings/api-keys", docs: "https://docs.together.ai",
    models: ["meta-llama/Llama-3.3-70B-Instruct-Turbo", "Qwen/Qwen3-235B-A22B-Instruct-2507-tput", "deepseek-ai/DeepSeek-V3", "moonshotai/Kimi-K2-Instruct"],
    notes: "Багато open-моделей, дешевий батчинг.",
  },
  {
    id: "fireworks", name: "Fireworks AI", category: "Швидкі", apiStyle: "openai",
    baseURL: "https://api.fireworks.ai/inference/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://fireworks.ai/account/api-keys", docs: "https://docs.fireworks.ai",
    models: ["accounts/fireworks/models/llama-v3p3-70b-instruct", "accounts/fireworks/models/deepseek-v3", "accounts/fireworks/models/kimi-k2-instruct", "accounts/fireworks/models/qwen3-235b-a22b"],
    notes: "Швидкий інференс + власні тюнені моделі.",
  },
  {
    id: "perplexity", name: "Perplexity Sonar", category: "З веб-пошуком", apiStyle: "openai", warn: "немає /models — вводьте модель вручну",
    baseURL: "https://api.perplexity.ai", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://www.perplexity.ai/settings/api", docs: "https://docs.perplexity.ai",
    models: ["sonar-pro", "sonar", "sonar-reasoning-pro", "sonar-deep-research"],
    notes: "Вбудований веб-пошук — ідеально для стадії «що зараз трендить».",
  },
  {
    id: "cohere", name: "Cohere", category: "Першорядні", apiStyle: "cohere",
    baseURL: "https://api.cohere.com", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://dashboard.cohere.com/api-keys", docs: "https://docs.cohere.com",
    models: ["command-a-03-2025", "command-r-plus-08-2024", "command-r7b-12-2024"],
    notes: "Command A — сильний у структурованих звітах.",
  },
  {
    id: "novita", name: "Novita AI", category: "Хмарні", apiStyle: "openai",
    baseURL: "https://api.novita.ai/v3/openai", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://novita.ai/settings/key-management", docs: "https://novita.ai/docs",
    models: ["deepseek/deepseek-v3.1", "meta-llama/llama-3.3-70b-instruct", "qwen/qwen3-235b-a22b-fp8", "moonshotai/kimi-k2-instruct"],
    notes: "Дешеві великі моделі, добрі ліміти.",
  },
  {
    id: "deepinfra", name: "DeepInfra", category: "Хмарні", apiStyle: "openai",
    baseURL: "https://api.deepinfra.com/v1/openai", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://deepinfra.com/dash/api_keys", docs: "https://deepinfra.com/docs",
    models: ["meta-llama/Llama-3.3-70B-Instruct", "deepseek-ai/DeepSeek-V3", "Qwen/Qwen3-235B-A22B", "mistralai/Mistral-Small-24B-Instruct-2501"],
    notes: "Одна з найнижчих цін за токен.",
  },
  {
    id: "hyperbolic", name: "Hyperbolic", category: "Хмарні", apiStyle: "openai",
    baseURL: "https://api.hyperbolic.xyz/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://app.hyperbolic.xyz/settings", docs: "https://docs.hyperbolic.xyz",
    models: ["Qwen/Qwen3-235B-A22B", "deepseek-ai/DeepSeek-V3-0324", "meta-llama/Llama-3.3-70B-Instruct"],
    notes: "Дешевий децентралізований інференс.",
  },
  {
    id: "nebius", name: "Nebius AI Studio", category: "Хмарні", apiStyle: "openai",
    baseURL: "https://api.studio.nebius.com/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://studio.nebius.com/settings/api-keys", docs: "https://docs.nebius.com",
    models: ["Qwen/Qwen3-235B-A22B", "deepseek-ai/DeepSeek-V3-0324", "meta-llama/Llama-3.3-70B-Instruct"],
    notes: "Стабільний європейський провайдер.",
  },
  {
    id: "sambanova", name: "SambaNova", category: "Швидкі", apiStyle: "openai",
    baseURL: "https://api.sambanova.ai/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://cloud.sambanova.ai/apis", docs: "https://docs.sambanova.ai",
    models: ["Meta-Llama-3.3-70B-Instruct", "DeepSeek-V3-0324", "Llama-4-Maverick-17B-128E-Instruct"],
    notes: "Дуже швидкий, є безкоштовний тариф.",
  },
  {
    id: "nvidia", name: "NVIDIA NIM", category: "Хмарні", apiStyle: "openai",
    baseURL: "https://integrate.api.nvidia.com/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://build.nvidia.com", docs: "https://docs.nvidia.com/nim",
    models: ["nvidia/nemotron-3-super-120b-a12b", "nvidia/nemotron-3-ultra-550b-a55b", "meta/llama-3.3-70b-instruct"],
    notes: "Безкоштовні кредити для розробників. Назви моделей звіряйте через «Підтягнути моделі».", warn: "перевірте назву моделі",
  },
  {
    id: "cloudflare", name: "Cloudflare Workers AI", category: "Хмарні", apiStyle: "openai",
    baseURL: "https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1", authStyle: "bearer", keyRequired: true,
    fields: [{ key: "account_id", label: "Account ID", placeholder: "abc123..." }],
    keyUrl: "https://dash.cloudflare.com/profile/api-tokens", docs: "https://developers.cloudflare.com/workers-ai",
    models: ["@cf/meta/llama-3.3-70b-instruct-fp8-fast", "@cf/qwen/qwen2.5-coder-32b-instruct", "@cf/meta/llama-3.1-8b-instruct"],
    notes: "Є щедрий безкоштовний денний ліміт нейронів.",
  },
  {
    id: "azure", name: "Azure OpenAI", category: "Хмарні", apiStyle: "azure",
    baseURL: "https://{resource}.openai.azure.com", authStyle: "api-key", keyRequired: true,
    apiVersion: "2024-10-21",
    fields: [{ key: "resource", label: "Назва ресурсу", placeholder: "my-openai-resource" }],
    keyUrl: "https://portal.azure.com", docs: "https://learn.microsoft.com/azure/ai-services/openai",
    models: ["gpt-4o", "gpt-4.1", "gpt-4o-mini"],
    notes: "У полі «модель» вказуйте назву deployment. Потрібен свій api-version за потреби.",
  },
  {
    id: "bedrock", name: "AWS Bedrock", category: "Хмарні", apiStyle: "openai",
    baseURL: "https://bedrock-runtime.{region}.amazonaws.com", authStyle: "bearer", keyRequired: true,
    fields: [{ key: "region", label: "Регіон", placeholder: "us-east-1", default: "us-east-1" }],
    keyUrl: "https://console.aws.amazon.com/bedrock", docs: "https://docs.aws.amazon.com/bedrock",
    models: ["anthropic.claude-sonnet-4-5", "meta.llama3-3-70b-instruct-v1:0", "amazon.nova-pro-v1:0"],
    notes: "Нативний Bedrock вимагає підпису SigV4. Найпростіше — поставити Bedrock-сумісний ключ через шлюз LiteLLM/Portkey і вказати його URL тут.",
    warn: "потребує SigV4 або шлюзу",
  },
  {
    id: "zai", name: "Z.ai (GLM / Zhipu)", category: "Азія", apiStyle: "openai",
    baseURL: "https://api.z.ai/api/paas/v4", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://z.ai/manage-apikey/apikey-list", docs: "https://docs.z.ai",
    models: ["glm-5.3", "glm-5.3-flash", "glm-5.2", "glm-4.6"],
    notes: "GLM близький до топ-моделей за суттєво нижчою ціною.",
  },
  {
    id: "moonshot", name: "Moonshot (Kimi)", category: "Азія", apiStyle: "openai",
    baseURL: "https://api.moonshot.ai/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://platform.moonshot.ai/console/api-keys", docs: "https://platform.moonshot.ai/docs",
    models: ["kimi-k3", "kimi-k2.7-code", "kimi-k2.6", "moonshot-v1-128k"],
    // Нові моделі Kimi приймають лише temperature = 1 і відповідають на інше
    // помилкою «invalid temperature: only 1 is allowed for this model».
    // Не надсилаємо параметр узагалі — тоді діє значення самого API.
    paramRules: [{ match: "kimi", omitTemperature: true }],
    notes: "Довгий контекст (128k+) — для великих досьє.",
  },
  {
    id: "dashscope", name: "Alibaba Qwen (DashScope)", category: "Азія", apiStyle: "openai",
    baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://bailian.console.alibabacloud.com", docs: "https://www.alibabacloud.com/help/model-studio",
    models: ["qwen3.8-max-0902", "qwen3.8-flash", "qwen3-max", "qwen-plus"],
    notes: "Міжнародний ендпоінт — dashscope-intl. Для Китаю замініть на dashscope.aliyuncs.com.",
  },
  {
    id: "minimax", name: "MiniMax", category: "Азія", apiStyle: "openai",
    baseURL: "https://api.minimax.io/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://platform.minimax.io/user-center/basic-information/interface-key", docs: "https://platform.minimax.io/docs",
    models: ["MiniMax-M3", "MiniMax-M2.7", "MiniMax-Text-01"],
    notes: "MiniMax — потужна й дешева родина моделей.",
  },
  {
    id: "siliconflow", name: "SiliconFlow", category: "Азія", apiStyle: "openai",
    baseURL: "https://api.siliconflow.com/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://cloud.siliconflow.com/account/ak", docs: "https://docs.siliconflow.com",
    models: ["Qwen/Qwen3-235B-A22B", "deepseek-ai/DeepSeek-V3", "moonshotai/Kimi-K2-Instruct", "zai-org/GLM-4.5"],
    notes: "Агрегатор дешевих open-моделей (є й .cn-домен).",
  },
  {
    id: "aimlapi", name: "AI/ML API", category: "Агрегатори", apiStyle: "openai",
    baseURL: "https://api.aimlapi.com/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://aimlapi.com/app/keys", docs: "https://docs.aimlapi.com",
    models: ["gpt-6-astra", "claude-sonnet-5", "deepseek-v4-pro", "gemini-3.8-flash"],
    notes: "400+ моделей через один ключ, включно з генерацією зображень.",
  },
  {
    id: "github", name: "GitHub Models", category: "Агрегатори", apiStyle: "openai",
    baseURL: "https://models.github.ai/inference", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://github.com/settings/tokens", docs: "https://docs.github.com/github-models",
    models: ["openai/gpt-4.1", "openai/gpt-4o-mini", "meta/Llama-3.3-70B-Instruct"],
    notes: "Безкоштовно з GitHub-токеном (PAT).", warn: "ендпоінт змінюється — звірте з доками",
  },
  {
    id: "ollama", name: "Ollama (локально)", category: "Локальні", apiStyle: "openai",
    baseURL: "http://127.0.0.1:11434/v1", authStyle: "bearer", keyRequired: false,
    keyUrl: "https://ollama.com/download", docs: "https://github.com/ollama/ollama/blob/main/docs/openai.md",
    models: ["llama3.2", "qwen3", "mistral", "deepseek-r1", "gemma3"],
    modelsEndpoint: "/models",
    notes: "Повністю безкоштовно й приватно. Спочатку: ollama pull qwen3",
  },
  {
    id: "lmstudio", name: "LM Studio (локально)", category: "Локальні", apiStyle: "openai",
    baseURL: "http://127.0.0.1:1234/v1", authStyle: "bearer", keyRequired: false,
    keyUrl: "https://lmstudio.ai", docs: "https://lmstudio.ai/docs/api/openai-api",
    models: ["local-model"],
    notes: "Увімкніть Local Server у LM Studio; модель підтягнеться списком.",
  },
  {
    id: "vllm", name: "vLLM (локальний сервер)", category: "Локальні", apiStyle: "openai",
    baseURL: "http://127.0.0.1:8000/v1", authStyle: "bearer", keyRequired: false,
    keyUrl: "", docs: "https://docs.vllm.ai",
    models: ["default"],
    notes: "vllm serve <model> — і працює як OpenAI API.",
  },
  {
    id: "llamacpp", name: "llama.cpp server", category: "Локальні", apiStyle: "openai",
    baseURL: "http://127.0.0.1:8080/v1", authStyle: "bearer", keyRequired: false,
    keyUrl: "", docs: "https://github.com/ggml-org/llama.cpp/tree/master/tools/server",
    models: ["default"],
    notes: "llama-server -m model.gguf -c 8192",
  },
  {
    id: "litellm", name: "LiteLLM Proxy", category: "Шлюзи", apiStyle: "openai",
    baseURL: "http://127.0.0.1:4000/v1", authStyle: "bearer", keyRequired: false,
    keyUrl: "", docs: "https://docs.litellm.ai",
    models: ["gpt-4o", "claude-sonnet-4-5", "deepseek-chat"],
    notes: "Один шлюз до 100+ провайдерів. Ідеально для Bedrock/Azure з корпоративними ключами.",
  },
  {
    id: "portkey", name: "Portkey Gateway", category: "Шлюзи", apiStyle: "openai",
    baseURL: "https://api.portkey.ai/v1", authStyle: "bearer", keyRequired: true,
    keyUrl: "https://app.portkey.ai", docs: "https://portkey.ai/docs",
    extraHeaders: { "x-portkey-provider": "openai" },
    models: ["gpt-4o", "claude-sonnet-4-5"],
    notes: "Шлюз з кешем, фолбеком і логами. Провайдера задають заголовком x-portkey-provider.",
  },
  {
    id: "custom", name: "Свій OpenAI-сумісний", category: "Свої", apiStyle: "openai",
    baseURL: "", authStyle: "bearer", keyRequired: false, keyUrl: "", docs: "",
    models: [], notes: "Будь-який OpenAI-сумісний ендпоінт: вкажіть base URL, ключ і моделі.",
  },
  {
    id: "mock", name: "Демо-рушій (офлайн)", category: "Службові", apiStyle: "mock",
    baseURL: "local://mock", authStyle: "none", keyRequired: false, keyUrl: "", docs: "",
    models: ["mock-analyst", "mock-fast"],
    notes: "Працює без ключа й без інтернету — щоб подивитися весь конвеєр і протестувати UI.",
  },
];

export const PRESET_BY_ID = new Map(PROVIDER_PRESETS.map((p) => [p.id, p]));
export const MOCK_PROVIDER_ID = "mock";
